### ISSUE TITLE
Optimizer: 2 sided face rendering material

### ISSUE THREAD

**Issue by memelotsqui** [M3-org/CharacterStudio#125]
When combining materials, there are some cases where user would like to have 2 side face rendering (more common in mtoon), we need to have an option box to support this when using the optimizer

**Comment by madjin** [comment]
![image](https://github.com/M3-org/CharacterStudio/assets/32600939/52c6a3d8-2bc1-46eb-9b2d-cc96f8e09933)
option box added, keep open?

**Comment by memelotsqui** [comment]
Closing as completed :) should be working now
