### ISSUE TITLE
UVs on non 0 to 1 space

### ISSUE THREAD

**Issue by memelotsqui** [M3-org/CharacterStudio#127]
There are cases were uvs are not in 0 to 1 space:

![image](https://github.com/M3-org/CharacterStudio/assets/1117257/c379b636-0821-4462-9481-8b28719480f2)

when this happens, generated atlas will have issues, as the uvs will jump to the next texture section in the atlas when merged

![image](https://github.com/M3-org/CharacterStudio/assets/1117257/885703e0-a453-45af-ac10-dab713b06ed5)

I think we can validate if uvs are higher than 1 to place the uvs in a range from 0 to 1  before merging all meshes and combining to atlas, this propbably fix the issue

**Comment by lalalune** [comment]
The better approach is to modulus all UV values by 1 to make sure they are floats between 0 and 1 before combining

**Comment by memelotsqui** [comment]
Completed with the commit referenced in the pervious comment, closing :)
