### ISSUE TITLE
add bone / triangle count information in optimizer page

### ISSUE THREAD

**Issue by madjin** [M3-org/CharacterStudio#132]

**Comment by memelotsqui** [comment]
![image](https://github.com/M3-org/CharacterStudio/assets/1117257/faa4b50a-75f4-4c0a-a68f-35131194f535)

Bone / triangles count should be working after merge :)

**Comment by madjin** [comment]
![image](https://github.com/user-attachments/assets/0b3e6cf7-98c4-49b8-8800-333b69ba47e6)
done
