### ISSUE TITLE
Optimizer gets rid of normal maps

### ISSUE THREAD

**Issue by memelotsqui** [M3-org/CharacterStudio#134]
normal maps are removed when using optimizer

**Comment by madjin** [comment]
this is still an issue, here's a vrm can test with posted in anata channel in discord: https://cdn.discordapp.com/attachments/1041270464271622234/1278860175565914184/los_santos_custom_-_type_gta_v.vrm?ex=66d256d9&is=66d10559&hm=beeac52af6f1cd6cdca62178b2f6eeee2aeb377d509826b6a772bb52856356f9&

**Comment by madjin** [comment]
Fixed and working
