### ISSUE TITLE
Manifest Modeltrait#isRestricted possibly broken?

### ISSUE THREAD

**Issue by Benjythebee** [M3-org/CharacterStudio#146]
In `CharacterManifestData.js` Function `isRestricted(targetModelTrait)`

I noticed `const traitTypes = getAsArray(trait.type);` Line 703.
variable `trait` comes from nowhere so it's always undefined

https://github.com/M3-org/CharacterStudio/blob/main/src/library/CharacterManifestData.js#L703

**Comment by memelotsqui** [comment]
Thanks for spotting this issue!, should be fixed now with:

https://github.com/M3-org/CharacterStudio/commit/58f66625f742de05cf894661aef772c56976804e
https://github.com/M3-org/CharacterStudio/commit/66fdf055813072a11d906a12fd50520ef1812d8b
