### ISSUE TITLE
New idle animation / animation selector

### ISSUE THREAD

**Issue by madjin** [M3-org/CharacterStudio#18]
Something sassy and expressive movement in order to give us more chances to debug / find clipping issues. Would be cool / useful to select different animations

**Comment by madjin** [comment]
we have drag and drop mixamo animation support, what'd be useful is to have 10 or so animations preloaded into character studio that you can quickly scroll through, on the bottom right side beneath culling distance / layer settings

**Comment by madjin** [comment]
ill find some animations

**Comment by memelotsqui** [comment]
Will also add ui button to block character looking at mouse for better debugging

**Comment by memelotsqui** [comment]
Closing as completed ( currently users can select animation, we just need to improve how they select them as #43 )
