### ISSUE TITLE
Support loading VRM0 format

### ISSUE THREAD

**Issue by memelotsqui** [M3-org/CharacterStudio#34]
There are some issues when trying to export vrm1 from blender with some models (Mainly hair)

Exported some hair models in vrm0 format and vrm1 format from blender and seems vrm0 has no issues, this is more notorious in hair, which include spring bones, exported vrm1 from blender is not including this information

![image](https://github.com/M3-org/CharacterStudio/assets/1117257/abb281e3-8740-445d-b41d-bf012287d30f)

Also, for some reason, exported hips for vrm1 format are rotated 18 degrees in t-pose, which is making the character look bald

![image](https://github.com/M3-org/CharacterStudio/assets/1117257/ccfa14e9-acc1-4d7b-bc40-ceb53dee38df)

Should be 0 like vrm0 exported model

![image](https://github.com/M3-org/CharacterStudio/assets/1117257/73816171-1100-4207-8d2b-f973c0fd8a07)

So the best approach is to also support vrm0 as import model. I still have to check how complex this is, if its too complex, to finish the objective in time, we can export vrm0 and reexport from unity as vrm1 as unity exports the models correctly:

(image shows hair working correctly, by exporting from blender as vrm0 then exporting from unity as vrm1)
![image](https://github.com/M3-org/CharacterStudio/assets/1117257/670bd7fb-e1b7-4afb-9207-f837cda1e5c0)

**Comment by fire** [comment]
You need to apply rotation of 180 to every single part of the model as vrm0 uses unity convention and vrm1 degrades to glb

**Comment by madjin** [comment]
this is now live / working
