### ISSUE TITLE
Move Animation Selection out of Trait Edit

### ISSUE THREAD

**Issue by memelotsqui** [M3-org/CharacterStudio#43]
Currently to test different animations we have to open any trait option to see animation options and mouse look.

![image](https://github.com/M3-org/CharacterStudio/assets/1117257/d765ceae-b401-424f-a082-a82905abca69)

User should be able to select animation without opening trait options, also it should be able to pause and play. Probably a new lower menu can fix this (include randomize, debug, animation selection, play, pause, mouselook)

something like this ( design can be improved )

![uiProposal](https://github.com/M3-org/CharacterStudio/assets/1117257/cdc1d05f-cfd2-49e6-9c60-efeb5fb12dac)

**Comment by madjin** [comment]
this is done
