### ISSUE TITLE
Add KTX2 export support

### ISSUE THREAD

**Issue by memelotsqui** [M3-org/CharacterStudio#72]
We should be able to choose to export ktx2 textures for optimized performance in supporting platforms

**Comment by madjin** [comment]
CLI program: https://github.com/BinomialLLC/basis_universal
![image](https://github.com/M3-org/CharacterStudio/assets/32600939/aabffc9c-2260-463c-961d-be3f192eb13d)
we want to add an optional checkbox on this screen, above `drag and drop - download` option.

**Comment by madjin** [comment]
its working :)
