### ISSUE TITLE
New icons for characters not working

### ISSUE THREAD

**Issue by madjin** [M3-org/CharacterStudio#99]
![Screenshot from 2023-12-27 19-56-30](https://github.com/M3-org/CharacterStudio/assets/32600939/16e66d2e-0d6a-4833-9ccc-fb09c7af65f8)
new branch not making icons of the characters

_Originally posted by @madjin in https://github.com/M3-org/CharacterStudio/issues/80#issuecomment-1870771423_

**Comment by madjin** [comment]
just tested latest version, issue still persists with old background
![image](https://github.com/M3-org/CharacterStudio/assets/32600939/a9a2845a-4a24-4bf9-b98b-9a7f71c5bc9d)

**Comment by memelotsqui** [comment]
fixed in #108 (close after merge)

**Comment by memelotsqui** [comment]
Closing after merge, should be working now
